#!/usr/bin/env python
"""Merge _trans_*.json files into app/content_translations.py."""

import json
from pathlib import Path

BASE = Path(__file__).parent

BATCHES = {
    "EN": ["_trans_en_a.json", "_trans_en_b.json"],
    "FR": ["_trans_fr_a.json", "_trans_fr_b.json"],
    "IT": ["_trans_it_a.json", "_trans_it_b.json"],
}

merged: dict[str, dict[str, str]] = {"EN": {}, "FR": {}, "IT": {}}

for lang, files in BATCHES.items():
    for fname in files:
        p = BASE / fname
        if p.exists():
            data = json.loads(p.read_text(encoding="utf-8"))
            merged[lang].update(data)
            print(f"  {fname}: {len(data)} articles")
        else:
            print(f"  {fname}: NOT FOUND (skipping)")

total = sum(len(v) for v in merged.values())
print(f"\nTotal translations: {total}")
for lang, data in merged.items():
    print(f"  {lang}: {len(data)} articles")

# Write content_translations.py
out = BASE / "app" / "content_translations.py"
lines = [
    '"""\n',
    'Pre-generated article content translations.\n',
    'Keys are article slugs, values are full HTML content strings.\n',
    'Generated by AI translation — do not edit manually.\n',
    '"""\n\n',
]
for lang, data in merged.items():
    lines.append(f"{lang}: dict[str, str] = {json.dumps(data, ensure_ascii=False, indent=4)}\n\n")

out.write_text("".join(lines), encoding="utf-8")
print(f"\nWritten to {out}")
